# Generated by Django 3.2.13 on 2022-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npp', models.IntegerField(blank=True, max_length=4000, null=True, verbose_name='№ п/п')),
                ('dateReg', models.DateField(blank=True, null=True, verbose_name='Дата регистрации приказа')),
                ('content', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Краткое содержание')),
                ('executor', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Ответственный за подготовку приказа')),
            ],
        ),
    ]
